n1 = int(input('Digite um valor: '))
a = n1 * 1
b = n1 * 2
c = n1 * 3
d = n1 * 4
e = n1 * 5
f = n1 * 6
g = n1 * 7
h = n1 * 8
i = n1 * 9
j = n1 * 10
print(n1,'x 1 = {}'.format(a))
print(n1,'x 2 = {}'.format(b))
print(n1,'x 3 = {}'.format(c))
print(n1,'x 4 = {}'.format(d))
print(n1,'x 5 = {}'.format(e))
print(n1,'x 6 = {}'.format(f))
print(n1,'x 7 = {}'.format(g))
print(n1,'x 8 = {}'.format(h))
print(n1,'x 9 = {}'.format(i))
print(n1,'x 10 = {}'.format(j))
